# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51cce316d120e140f561dbd1af2e16cb75d86937a50cbe9ac7017e2e283206a36c6f3259ff33bafa6175d41f8f9142a492eda1800f32fc8a2f2eac6c96152224

test:
  secret_key_base: bab1fef471a43c47d7687786e7df5b453d82f4a2eb77612e0a7b5bde22d7db7886d76ee04bc6faa3d75f88189f8d5a5d18cd7f7eb53d836c6664f731f3f473ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
